# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arctic_inference.suffix_decoding.proto import suffix_decoding_pb2 as arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arctic_inference/suffix_decoding/proto/suffix_decoding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuffixDecodingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRequest = channel.unary_unary(
                '/arctic_inference.suffix_decoding.SuffixDecodingService/StartRequest',
                request_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StartRequestMsg.SerializeToString,
                response_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
                _registered_method=True)
        self.StopRequest = channel.unary_unary(
                '/arctic_inference.suffix_decoding.SuffixDecodingService/StopRequest',
                request_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StopRequestMsg.SerializeToString,
                response_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
                _registered_method=True)
        self.AddTokens = channel.unary_unary(
                '/arctic_inference.suffix_decoding.SuffixDecodingService/AddTokens',
                request_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.AddTokensMsg.SerializeToString,
                response_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
                _registered_method=True)
        self.BatchAddTokens = channel.unary_unary(
                '/arctic_inference.suffix_decoding.SuffixDecodingService/BatchAddTokens',
                request_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchAddTokensMsg.SerializeToString,
                response_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
                _registered_method=True)
        self.Speculate = channel.unary_unary(
                '/arctic_inference.suffix_decoding.SuffixDecodingService/Speculate',
                request_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.SpeculateMsg.SerializeToString,
                response_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.SpeculateResponse.FromString,
                _registered_method=True)
        self.BatchSpeculate = channel.unary_unary(
                '/arctic_inference.suffix_decoding.SuffixDecodingService/BatchSpeculate',
                request_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchSpeculateMsg.SerializeToString,
                response_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchSpeculateResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/arctic_inference.suffix_decoding.SuffixDecodingService/GetStats',
                request_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.SerializeToString,
                response_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StatsResponse.FromString,
                _registered_method=True)


class SuffixDecodingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartRequest(self, request, context):
        """Start a new request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRequest(self, request, context):
        """Stop a request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTokens(self, request, context):
        """Add tokens to a request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchAddTokens(self, request, context):
        """Add tokens to multiple requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Speculate(self, request, context):
        """Speculate for a single request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSpeculate(self, request, context):
        """Speculate for multiple requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get cache statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuffixDecodingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRequest,
                    request_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StartRequestMsg.FromString,
                    response_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.SerializeToString,
            ),
            'StopRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRequest,
                    request_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StopRequestMsg.FromString,
                    response_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.SerializeToString,
            ),
            'AddTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTokens,
                    request_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.AddTokensMsg.FromString,
                    response_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.SerializeToString,
            ),
            'BatchAddTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchAddTokens,
                    request_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchAddTokensMsg.FromString,
                    response_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.SerializeToString,
            ),
            'Speculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Speculate,
                    request_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.SpeculateMsg.FromString,
                    response_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.SpeculateResponse.SerializeToString,
            ),
            'BatchSpeculate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSpeculate,
                    request_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchSpeculateMsg.FromString,
                    response_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchSpeculateResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
                    response_serializer=arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arctic_inference.suffix_decoding.SuffixDecodingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arctic_inference.suffix_decoding.SuffixDecodingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuffixDecodingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arctic_inference.suffix_decoding.SuffixDecodingService/StartRequest',
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StartRequestMsg.SerializeToString,
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arctic_inference.suffix_decoding.SuffixDecodingService/StopRequest',
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StopRequestMsg.SerializeToString,
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arctic_inference.suffix_decoding.SuffixDecodingService/AddTokens',
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.AddTokensMsg.SerializeToString,
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchAddTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arctic_inference.suffix_decoding.SuffixDecodingService/BatchAddTokens',
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchAddTokensMsg.SerializeToString,
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Speculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arctic_inference.suffix_decoding.SuffixDecodingService/Speculate',
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.SpeculateMsg.SerializeToString,
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.SpeculateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSpeculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arctic_inference.suffix_decoding.SuffixDecodingService/BatchSpeculate',
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchSpeculateMsg.SerializeToString,
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.BatchSpeculateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arctic_inference.suffix_decoding.SuffixDecodingService/GetStats',
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.Empty.SerializeToString,
            arctic__inference_dot_suffix__decoding_dot_proto_dot_suffix__decoding__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
